#!/usr/bin/env node

var Promise 	= require('bluebird');
var config 		= require(__dirname + '/config.json');

var exec 			= Promise.promisify(require('child_process').exec);
var todo 			= require('commander');
var keychain 	= require(__dirname + '/lib/keychain-promise');

var githubKeychain = {
	account: config.github.login,
	service: 'github.com',
	type: 'internet'
}

keychain.getPassword(githubKeychain).then(function (password) {
	console.log('Password is %s.', password);
}).catch(function (error) {
	console.error(error);
});

 
// executes `pwd`
exec("git rev-parse --show-toplevel")
.then(function (repo) {





}).catch(function (error) {
	console.error('Unable to locate git repository. todo must be run within a git repo.')
});